---
development:
  cloud_name: dd7bqhq3q
  api_key: '518833358718444'
  api_secret: qk-MjZlWQUoVuF6HeddZ4sWo9pc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dd7bqhq3q
  api_key: '518833358718444'
  api_secret: qk-MjZlWQUoVuF6HeddZ4sWo9pc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dd7bqhq3q
  api_key: '518833358718444'
  api_secret: qk-MjZlWQUoVuF6HeddZ4sWo9pc
  enhance_image_tag: true
  static_image_support: false
